livestreamcurator/api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework.authtoken import views as drf_views

from . import views

app_name = 'api'

urlpatterns = [
    path('auth', drf_views.obtain_auth_token, name='auth'),
    path('user', views.User.as_view(), name='user'),
    path('users', views.Users.as_view(), name='users'),
    path('users/<int:user_id>/livestreams', views.UserLivestreams.as_view(), name='user_livestreams'),
    path('livestreams/<int:pk>', views.Livestreamer.as_view(), name='update_livestream'),
    #path('users/<int:user_id>/groups', views.UserLivestreamGroups.as_view(), name='user_livestream_groups'),
    
]

urlpatterns = format_suffix_patterns(urlpatterns)

livestreamcurator/livestream/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'livestream'

urlpatterns = [
    path('', views.home, name='home'),
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/add/', views.modifyStream, name='add'),
    path('<str:username>/delete/', views.deleteStream, name='delete'),
    path('<str:username>/edit/<str:streamer>/', views.modifyStream, name='edit'),
    path('<str:username>/group/create/', views.modifyGroup, name='group_create'),
    path('<str:username>/group/edit/<str:groupName>/', views.modifyGroup, name='group_edit'),
    path('<str:username>/group/delete/', views.deleteGroup, name='group_delete'),
    path('<str:username>/group/show/<str:groupName>/', views.showGroup, name='group_show'),
    path('<str:username>/group/delete/<str:groupName>/', views.deleteFromGroup, name='group_delete_member'),
]

livestreamcurator/livestream/models.py
from django.db import models

# Create your models here.

livestreamcurator/livestream/forms.py
from django import forms
from .models import Livestream, LivestreamGroup
from django.contrib.auth.models import User
from . import twitchAPI as TwitchAPI

class LivestreamForm(forms.ModelForm):
    class Meta:
        model = Livestream
        exclude = ['user', 'twitchUserId']
        labels = {
            'twitchUsername': 'Twitch Username'
        }
    # verifies livestream form fields are unique to user
    # have to override because we don't ask for user in form which normally 
    # excludes user from validation
    def validate_unique(self):
        exclude = self._get_validation_exclusions()
        exclude.remove('user') # allow checking against the missing attribute
        
        try:
            self.instance.validate_unique(exclude=exclude)
        except forms.ValidationError as e:
            self._update_errors(e.message_dict)
    # verifies twitch username is valid
    #def clean_twitchUsername(self):
    #    cleaned_twitchUsername = self.cleaned_data['twitchUsername']
        
     #   if not TwitchAPI.userValid(cleaned_twitchUsername):
     #       raise forms.ValidationError('Twitch username not found.')
     #   return cleaned_twitchUsername
        
class LivestreamGroupForm(forms.ModelForm):
    class Meta:
        model = LivestreamGroup
        exclude = ['user']
        
    # verifies livestreamGroup form fields are unique to user
    # have to override because we don't ask for user in form which normally 
    # excludes user from validation
    def validate_unique(self):
        exclude = self._get_validation_exclusions()
        exclude.remove('user') # allow checking against the missing attribute

        try:
            self.instance.validate_unique(exclude=exclude)
        except forms.ValidationError as e:
            self._update_errors(e.message_dict)

livestreamcurator/livestream/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404, HttpResponseRedirect
from django.core.exceptions import PermissionDenied
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.urls import reverse
from django.conf import settings
from .models import Livestream, LivestreamGroup
from .forms import LivestreamForm, LivestreamGroupForm
from . import twitchAPI as TwitchAPI


# Create your views here.

# split livestreams into live and offline
# output: live and offline usernames
def liveAndOfflineStreams(livestreams):
    if livestreams is None or livestreams.count() == 0:
        return [], []
    livestreamLookup = dict()
    for livestream in livestreams:
        livestreamLookup[livestream.twitchUserId] = livestream
    userIds = [stream.twitchUserId for stream in livestreams]
    streamStatuses = TwitchAPI.usersOnline(userIds)
    liveStreams = []
    offlineStreams = []
    for userId in streamStatuses:
        live = streamStatuses[userId]
        stream = livestreamLookup[userId]
        if live:
            liveStreams.append(stream)
        else:
            offlineStreams.append(stream)
    return liveStreams, offlineStreams
    
def liveAndOfflineGroups(groups, liveStreams):
    liveGroups = set()
    for livestream in liveStreams:
        for group in livestream.livestreamgroup_set.all():
            liveGroups.add(group)
            
    offlineGroups = []
    for group in groups:
        if group not in liveGroups:
            offlineGroups.append(group)
            
    liveGroups = list(liveGroups)
    return liveGroups, offlineGroups
        
        
def home(request):
    if request.user.is_authenticated:
        return profile(request, request.user.username)
    else:
        return render(request, 'livestream/home.html')
    
# need live and offline group
def profile(request, username):
    user = request.user
    ownPage = user.is_authenticated and user.username == username
    pageUser = get_object_or_404(User.objects.prefetch_related('livestream_set', 'livestreamgroup_set'), username=username)
    livestreams = pageUser.livestream_set.all().prefetch_related('livestreamgroup_set')
    groups = pageUser.livestreamgroup_set.all()
    live, offline = liveAndOfflineStreams(livestreams)
    liveGroups, offlineGroups = liveAndOfflineGroups(groups, live)
    context = {'ownPage': ownPage, 'pageUser': pageUser, 'live': live, 'offline': offline, 'liveGroups': liveGroups, 'offlineGroups': offlineGroups}
    return render(request, 'livestream/profile.html', context)
    
@login_required
def modifyStream(request, username, streamer=None):
    # check if post request or get request
    # process form if post
    authorized = request.user.username == username
    if not authorized:
        raise PermissionDenied
    if streamer is None:
        # adding
        # retrieve twitchId
        
        livestream = Livestream(user=request.user)
    else:
        # editing
        livestream = get_object_or_404(Livestream, user=request.user, name=streamer)
    if request.method == 'POST':
        form = LivestreamForm(request.POST, instance=livestream)
        
        if form.is_valid():
            livestream = form.save(commit=False)
            if streamer is None:
                userId = TwitchAPI.userId(livestream.twitchUsername)
                if userId is None:
                    raise Http404('Could not find Twitch user id from username')
                livestream.twitchUserId = userId
            livestream.save()
            return HttpResponseRedirect(reverse('livestream:profile', args=(request.user.username,)))
    else:
        form = LivestreamForm(instance=livestream)
        
    return render(request, 'livestream/modifyStream.html', {'form': form, 'add': streamer is None})
    
@login_required
@require_http_methods(['POST'])
def deleteStream(request, username):
    authorized = request.user.username == username
    if not authorized:
        raise PermissionDenied
    if 'id' in request.POST:
        livestream = get_object_or_404(Livestream, pk=request.POST['id'])
        livestream.delete()
    return HttpResponseRedirect(reverse('livestream:profile', args=(request.user.username,)))
    
@login_required
def modifyGroup(request, username, groupName=None):
    authorized = request.user.username == username
    if not authorized:
        raise PermissionDenied
    if groupName is None:
        # adding
        livestreamGroup = LivestreamGroup(user=request.user)
    else:
        # editing
        livestreamGroup = get_object_or_404(LivestreamGroup, user=request.user, name=groupName)
    if request.method == 'POST':
        form = LivestreamGroupForm(request.POST, instance=livestreamGroup)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('livestream:profile', args=(request.user.username,)))
    else:
        form = LivestreamGroupForm(instance=livestreamGroup)    
        
    return render(request, 'livestream/modifyGroup.html', {'form': form, 'add': groupName is None})

@login_required
@require_http_methods(['POST'])
def deleteGroup(request, username):
    authorized = request.user.username == username
    if not authorized:
        raise PermissionDenied
    if 'id' in request.POST:
        livestreamGroup = get_object_or_404(LivestreamGroup, pk=request.POST['id'])
        livestreamGroup.delete()
    return HttpResponseRedirect(reverse('livestream:profile', args=(request.user.username,)))
  
@login_required
@require_http_methods(['POST'])  
def deleteFromGroup(request, username, groupName):
    authorized = request.user.username == username
    if not authorized:
        raise PermissionDenied
    if 'id' in request.POST:
        livestream = get_object_or_404(Livestream, pk=request.POST['id'])
        livestreamGroup = get_object_or_404(LivestreamGroup, user=request.user, name=groupName)
        livestreamGroup.livestreams.remove(livestream)
    return HttpResponseRedirect(reverse('livestream:group_show', args=(request.user.username,groupName,)))
    
def showGroup(request, username, groupName):
    user = request.user
    ownPage = user.is_authenticated and user.username == username
    pageUser = get_object_or_404(User, username=username)
    group = get_object_or_404(LivestreamGroup, user=pageUser, name=groupName)
    context = {'ownPage': ownPage, 'pageUser': pageUser, 'group': group}
    return render(request, 'livestream/group.html', context)

livestreamcurator/livestream/templates/livestream/group.html
{% extends 'livestreamcurator/base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'livestream/styles.css' %}" />
{% endblock head %}

{% block title %}{{ pageUser.get_username }}{% endblock title %}

{% block content %}
<div class="d-flex justify-content-between">
    <div class="left">
        <a href="{% url 'livestream:profile' pageUser.get_username%}">{{ pageUser.get_username }}'s livestream collection</a>
    </div>
    {% if ownPage is True %}
        <div class="right">
            <a class="" href="{% url 'livestream:group_create' user.get_username%}">Create group</a>
            <a href="{% url 'livestream:group_edit' user.get_username group.name %}">Edit</a>
        </div>
    {% endif %}
</div>
<div class="d-flex justify-content-center">
    {{ group.name }}
</div>
<div class="d-flex justify-content-around flex-wrap">
    {% include "livestream/livestreamPlayer.html" with livestreams=group.livestreams.all platform="twitch" members=True %}
</div>
{% endblock content %}

livestreamcurator/livestream/templates/livestream/home.html
{% extends 'livestreamcurator/base.html' %}

{% block title %}Livestream Curator{% endblock %}

{% block content %}
{% endblock content%}

livestreamcurator/livestream/templates/livestream/livestreamGroups.html
{% comment %}
parameters: groups pageUser user ownPage
{% endcomment %}

{% if groups %}
    {% for group in groups %}
    <div class="livestreamGroup">
        <div class="livestreamGroup_name d-flex
            {% if ownPage is True %}
            justify-content-between">
            <div class="placeholder">
            </div>
            {% else %}
            justify-content-center">
            {% endif %}
            <a href="{% url 'livestream:group_show' pageUser.get_username group.name %}">
            {{ group.name }}
            </a>
            {% if ownPage is True %}
                <form action="{% url 'livestream:group_delete' user.get_username %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="id" value="{{ group.id }}">
                    <button type="submit" class="close" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                </form>
            {% endif %}
        </div>
        {% include "livestream/livestreamPlayer.html" with livestreams=group.livestreams.all thumbnail=True platform="twitch" %}
    </div>
    {% endfor %}
{% endif %}

livestreamcurator/livestream/templates/livestream/livestreamPlayer.html
{% comment %}
parameters: livestreams platform thumbnail ownPage members
if you pass thumbnail, you don't need ownPage
{% endcomment %}

{% if livestreams %}
    {% for livestream in livestreams %}
        <div class="livestream">
            {% if not thumbnail %}
            <div class="livestream_name d-flex 
            {% if ownPage is True %}
            justify-content-between">
            <div class="placeholder">
            </div>
            <a href="{% url 'livestream:edit' user.get_username livestream.name%}" >
            {% else %}
            justify-content-center">
            {% endif %}
            {{ livestream.name }}
            {% if ownPage is True %}
            </a>
            <form action="{% if group %}{% url 'livestream:group_delete_member' user.get_username group.name %}{% else %}{% url 'livestream:delete' user.get_username %}{% endif %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="id" value="{{ livestream.id }}">
                    <button type="submit" class="close" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
            </form>
            {% endif %}
            </div>
            {% endif %}
            {% if platform == "twitch" %}
                <iframe
                    src="http://player.twitch.tv/?channel={{ livestream.twitchUsername }}&muted=true"
                    height="300"
                    width="400"
                    frameborder="0"
                    scrolling="no"
                    allowfullscreen="true">
                </iframe>
            {% endif %}
        </div>
    {% endfor %}
{% endif %}

livestreamcurator/livestream/templates/livestream/modifyGroup.html
{% extends 'livestreamcurator/base.html' %}

{% block title %}
{% if add %}Create
{% else %}Edit
{% endif %} group
{% endblock title %}

{% block content %}
<div class="d-flex justify-content-center">
    <div class="d-flex flex-column">
        <div class="text-center">
            <h2>
            {% if add %}
            Create
            {% else %}
            Edit
            {% endif %} group
            <h2>
        </div>
        <form method="post" class="d-flex flex-column align-items-center">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="">Save</button>
        </form>
    </div>
</div>
{% endblock content %}

livestreamcurator/livestream/templates/livestream/modifyStream.html
{% extends 'livestreamcurator/base.html' %}

{% load static %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'livestream/styles.css' %}" />
{% endblock head %}

{% block title %}
{% if add %}Add
{% else %}Edit
{% endif %} live streamer
{% endblock %}

{% block content %}
<h2>{% if add %}Add
{% else %}Edit
{% endif %} live streamer</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save</button>
</form>
{% endblock %}

livestreamcurator/livestream/templates/livestream/profile.html
{% extends 'livestreamcurator/base.html' %}
{% block title %}Livestream Curator: {{ pageUser.get_username }}{% endblock title %}

{% block content %}
<div class="d-flex justify-content-between">
    <div class="left">
        <a href="{% url 'livestream:profile' pageUser.get_username%}">{{ pageUser.get_username }}'s livestream collection</a>
    </div>
    {% if ownPage is True %}
        <div class="right">
            <a class="" href="{% url 'livestream:group_create' user.get_username%}">Create group</a>
            <a href="{% url 'livestream:add' pageUser.get_username %}">Add</a>
        </div>
    {% endif %}
</div>
<div class="d-flex justify-content-center">
    <h3>Live<h3>
</div>
<div class="d-flex justify-content-around flex-wrap">
    {% include "livestream/livestreamGroups.html" with groups=liveGroups pageUser=pageUser user=user ownPage=ownPage %}
    {% include "livestream/livestreamPlayer.html" with livestreams=live platform="twitch" ownPage=ownPage user=user %}
</div>
<hr />
<div class="d-flex justify-content-center">
    <h3>Offline<h3>
</div>
<div class="d-flex justify-content-around flex-wrap">
    {% include "livestream/livestreamGroups.html" with groups=offlineGroups pageUser=pageUser user=user ownPage=ownPage %}
    {% include "livestream/livestreamPlayer.html" with livestreams=offline platform="twitch" ownPage=ownPage user=user %}
</div>
{% endblock content %}