livestreamcurator/api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework.authtoken import views as drf_views

from . import views

app_name = 'api'

urlpatterns = [
    path('auth', drf_views.obtain_auth_token, name='auth'),
    path('user', views.User.as_view(), name='user'),
    path('users', views.Users.as_view(), name='users'),
    path('users/<int:user_id>/livestreams', views.UserLivestreams.as_view(), name='user_livestreams'),
    path('livestreams/<int:pk>', views.Livestreamer.as_view(), name='update_livestream'),
    #path('users/<int:user_id>/groups', views.UserLivestreamGroups.as_view(), name='user_livestream_groups'),
    
]

urlpatterns = format_suffix_patterns(urlpatterns)

livestreamcurator/livestream/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'livestream'

urlpatterns = [
    path('', views.home, name='home'),
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/add/', views.modifyStream, name='add'),
    path('<str:username>/delete/', views.deleteStream, name='delete'),
    path('<str:username>/edit/<str:streamer>/', views.modifyStream, name='edit'),
    path('<str:username>/group/create/', views.modifyGroup, name='group_create'),
    path('<str:username>/group/edit/<str:groupName>/', views.modifyGroup, name='group_edit'),
    path('<str:username>/group/delete/', views.deleteGroup, name='group_delete'),
    path('<str:username>/group/show/<str:groupName>/', views.showGroup, name='group_show'),
    path('<str:username>/group/delete/<str:groupName>/', views.deleteFromGroup, name='group_delete_member'),
]

livestreamcurator/livestreamcurator/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from . import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include('api.urls')),
    path('', TemplateView.as_view(template_name='index.html')),
]

livestreamcurator/livestreamcurator/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']
        widgets = {
            'password': forms.PasswordInput(),
        }

livestreamcurator/livestreamcurator/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login

from .forms import UserForm

# Create your views here.
def signup(request):
    # check if post request or get request
    # process form if post
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()
            user = authenticate(username = user.username, password = password)
            if user is not None:
                login(request, user)
            return HttpResponseRedirect(reverse('livestream:home'))
    else:
        form = UserForm()
        
    return render(request, 'registration/signup.html', {'form': form})

livestreamcurator/templates/livestreamcurator/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}{% endblock title %}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
        {% block head %}{% endblock head %}
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'livestream/styles.css' %}" />
        
    </head>

    <body>
        <!-- header -->
        <!-- A grey horizontal navbar that becomes vertical on small screens -->
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
          <a class="nav-link navbar-brand" href="{% url 'livestream:home' %}">Livestream Curator</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <!-- Links -->
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <!-- Dropdown -->
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="{% url 'livestream:profile' user.username %}" id="navbardrop" data-toggle="dropdown">
                    {{ user.username }}
                  </a>
                  <div class="dropdown-menu bg-dark dropdown-menu-right">
                    <a class="dropdown-item text-white bg-dark" href="{% url 'logout' %}">Log Out</a>
                  </div>
                </li>
                {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'signup' %}">Sign up</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'login' %}">Log in</a>
                </li>
                {% endif %}
              </ul>
          </div>

        </nav>
        <div class="container-fluid bg-secondary text-color">
            {% block content %}{% endblock content %}
        </div>
    </body>
</html>